language: java
global:
  - secure: "QJkoeIk5GU41c1ir/uZML6KgVDUoiw0K45sNal7rtW/uhRvT/HrmG3iLGmw8qcbMN4F16Tr/GITVkmUy20LiPitm8AjO4QOIXgjPKMOHpWfpQnBwgLCRJeDcIoxwouKpOmZYd7i0EURvvFFxn2LeksepSSAS/dgDVi/hqSZLx70="
  - secure: "Xr1jaoe6cDB2GrSCsrh3mDy6M9DvfwjvzCWXAWl8O0uZggtNgY/f86/K7zBMlKjL4/hkXi+/BZnTXZWay9Azi97+Gt15WOcRZg1+JgnAJhOlJ5FM+fVoIotKPldjM1O56qoIuOdmE0OpPQiA19MNOJwz0deGost/3QVZMpObd+g="
before_install:
  - gcc --version
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$SSH_KEY" > ~/.ssh/id_rsa.pub
  - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa*
  - eval `ssh-agent -s`
  - ssh-add ~/.ssh/id_rsa
  - echo "machine bitbucket.org\n login $CI_DEPLOY_USERNAME\n password $CI_DEPLOY_PASSWORD\n" >> ~/.netrc
  - sudo apt-get install cmake swig build-essential
install:
  - sh scripts/install.sh
